services:

  dense-retrieval:
    build:
      context: ./services/dense-retrieval
      dockerfile: Dockerfile
    container_name: ledger-dense-retrieval
    ports:
      - "8000:8000"
    environment:
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
      LANGFUSE_HOST: ${LANGFUSE_HOST}
    restart: unless-stopped

  reasoning:
    build:
      context: ./services/reasoning
      dockerfile: Dockerfile
    container_name: ledger-reasoning
    ports:
      - "8001:8000"
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      RETRIEVAL_API_URL: http://dense-retrieval:8000
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
      LANGFUSE_HOST: ${LANGFUSE_HOST}      
    depends_on:
      - dense-retrieval
    restart: unless-stopped

  doc-processor:
    build:
      context: ./services/doc-processor-api
      dockerfile: Dockerfile
    container_name: ledger-doc-processor
    ports:
      - "8002:8000"
    restart: unless-stopped

  validator:
    build:
      context: ./services/validator-service
      dockerfile: Dockerfile
    container_name: ledger-validator
    ports:
      - "8004:8000"
    environment:
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
      LANGFUSE_HOST: ${LANGFUSE_HOST}
      restart: unless-stopped

  eval-service:
    build:
      context: ./services/eval-service
      dockerfile: Dockerfile
    container_name: ledger-eval-service
    ports:
      - "8005:8000"
    environment:
      BENCHMARK_PATH: /app/data/benchmark_100.json
      ORCHESTRATOR_URL: http://orchestrator:8000
      LANGFUSE_HOST: ${LANGFUSE_HOST}
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
    depends_on:
      - orchestrator
    restart: unless-stopped
  
  orchestrator:
    build:
      context: ./services/orchestrator
      dockerfile: Dockerfile
    container_name: ledger-orchestrator
    ports:
      - "8003:8000"
    environment:
      DOC_PROCESSOR_URL: http://doc-processor:8000
      RETRIEVAL_URL: http://dense-retrieval:8000
      REASONING_URL: http://reasoning:8000
      VALIDATOR_URL: http://validator:8000
      LANGFUSE_HOST: ${LANGFUSE_HOST}
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
    depends_on:
      - dense-retrieval
      - reasoning
      - doc-processor
      - validator
    restart: unless-stopped

  ui:
    build:
      context: ./services/ui
      dockerfile: Dockerfile
    container_name: ledger-ui
    ports:
      - "7860:7860"
    depends_on:
      - orchestrator
    restart: unless-stopped